import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useTranslation } from "react-i18next";
import { supabase } from "@/integrations/supabase/client";
import { useSpokenLanguages } from "@/hooks/useSpokenLanguages";

interface TranslatedContent {
  translatedText: string | null;
  isAutoGenerated: boolean;
  isTranslated: boolean;
  displayLanguage: string | null;
}

/**
 * Fetches translated content for a given entity + field in the user's preferred language.
 * Falls back to original text if no translation exists.
 */
export function useContentTranslation(
  entityType: string,
  entityId: string | undefined,
  fieldName: string,
  originalText: string | null | undefined
): TranslatedContent & { isLoading: boolean; requestTranslation: () => void } {
  const { i18n } = useTranslation();
  const lang = i18n.language;
  const qc = useQueryClient();

  const { data, isLoading } = useQuery({
    queryKey: ["content-translation", entityType, entityId, fieldName, lang],
    queryFn: async () => {
      if (!entityId) return null;
      const { data: row } = await supabase
        .from("content_translations")
        .select("translated_text, auto_generated")
        .eq("entity_type", entityType)
        .eq("entity_id", entityId)
        .eq("field_name", fieldName)
        .eq("language_code", lang)
        .maybeSingle();
      return row;
    },
    enabled: !!entityId && lang !== "en", // Only fetch translations for non-default languages
    staleTime: 5 * 60_000,
  });

  const translateMut = useMutation({
    mutationFn: async () => {
      if (!entityId || !originalText) return;
      const { data: result, error } = await supabase.functions.invoke("translate-content", {
        body: {
          entityType,
          entityId,
          fieldName,
          text: originalText,
          targetLanguage: lang,
        },
      });
      if (error) throw error;
      return result;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["content-translation", entityType, entityId, fieldName, lang] });
    },
  });

  if (lang === "en" || !entityId) {
    return {
      translatedText: originalText ?? null,
      isAutoGenerated: false,
      isTranslated: false,
      isLoading: false,
      requestTranslation: () => translateMut.mutate(),
    };
  }

  return {
    translatedText: data?.translated_text ?? originalText ?? null,
    isAutoGenerated: data?.auto_generated ?? false,
    isTranslated: !!data?.translated_text,
    isLoading,
    requestTranslation: () => translateMut.mutate(),
  };
}

/**
 * Batch-fetches translations for multiple fields of an entity.
 */
export function useContentTranslations(
  entityType: string,
  entityId: string | undefined,
  fields: { fieldName: string; originalText: string | null | undefined }[]
) {
  const { i18n } = useTranslation();
  const lang = i18n.language;

  const { data: translations = [], isLoading } = useQuery({
    queryKey: ["content-translations-batch", entityType, entityId, lang],
    queryFn: async () => {
      if (!entityId) return [];
      const { data } = await supabase
        .from("content_translations")
        .select("field_name, translated_text, auto_generated")
        .eq("entity_type", entityType)
        .eq("entity_id", entityId)
        .eq("language_code", lang);
      return data ?? [];
    },
    enabled: !!entityId && lang !== "en",
    staleTime: 5 * 60_000,
  });

  const result: Record<string, { text: string | null; isTranslated: boolean; isAuto: boolean }> = {};
  for (const f of fields) {
    const match = translations.find((t: any) => t.field_name === f.fieldName);
    result[f.fieldName] = {
      text: match ? match.translated_text : (f.originalText ?? null),
      isTranslated: !!match,
      isAuto: match?.auto_generated ?? false,
    };
  }

  return { translations: result, isLoading };
}
