import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useTranslation } from "react-i18next";
import { supabase } from "@/integrations/supabase/client";
import { useSpokenLanguages } from "@/hooks/useSpokenLanguages";

interface TranslatedContent {
  translatedText: string | null;
  isAutoGenerated: boolean;
  isTranslated: boolean;
  displayLanguage: string | null;
}

/**
 * Fetches translated content for a given entity + field.
 * Fallback chain: preferredLanguage → spokenLanguages → original.
 */
export function useContentTranslation(
  entityType: string,
  entityId: string | undefined,
  fieldName: string,
  originalText: string | null | undefined
): TranslatedContent & { isLoading: boolean; requestTranslation: () => void } {
  const { i18n } = useTranslation();
  const lang = i18n.language;
  const qc = useQueryClient();
  const { spokenCodes } = useSpokenLanguages();

  // Fetch ALL translations for this entity+field so we can do fallback
  const { data: allTranslations, isLoading } = useQuery({
    queryKey: ["content-translation-all", entityType, entityId, fieldName],
    queryFn: async () => {
      if (!entityId) return [];
      const { data } = await supabase
        .from("content_translations")
        .select("language_code, translated_text, auto_generated")
        .eq("entity_type", entityType)
        .eq("entity_id", entityId)
        .eq("field_name", fieldName);
      return data ?? [];
    },
    enabled: !!entityId && lang !== "en",
    staleTime: 5 * 60_000,
  });

  const translateMut = useMutation({
    mutationFn: async () => {
      if (!entityId || !originalText) return;
      const { data: result, error } = await supabase.functions.invoke("translate-content", {
        body: {
          entityType,
          entityId,
          fieldName,
          text: originalText,
          targetLanguage: lang,
        },
      });
      if (error) throw error;
      return result;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["content-translation-all", entityType, entityId, fieldName] });
    },
  });

  if (lang === "en" || !entityId) {
    return {
      translatedText: originalText ?? null,
      isAutoGenerated: false,
      isTranslated: false,
      displayLanguage: "en",
      isLoading: false,
      requestTranslation: () => translateMut.mutate(),
    };
  }

  // Fallback chain: preferred → spoken → original
  const preferred = allTranslations?.find((t: any) => t.language_code === lang);
  if (preferred) {
    return {
      translatedText: preferred.translated_text,
      isAutoGenerated: preferred.auto_generated ?? false,
      isTranslated: true,
      displayLanguage: lang,
      isLoading,
      requestTranslation: () => translateMut.mutate(),
    };
  }

  // Check spoken languages
  for (const code of spokenCodes) {
    if (code === lang || code === "en") continue;
    const match = allTranslations?.find((t: any) => t.language_code === code);
    if (match) {
      return {
        translatedText: match.translated_text,
        isAutoGenerated: match.auto_generated ?? false,
        isTranslated: true,
        displayLanguage: code,
        isLoading,
        requestTranslation: () => translateMut.mutate(),
      };
    }
  }

  // Fallback to original
  return {
    translatedText: originalText ?? null,
    isAutoGenerated: false,
    isTranslated: false,
    displayLanguage: null,
    isLoading,
    requestTranslation: () => translateMut.mutate(),
  };
}

/**
 * Batch-fetches translations for multiple fields of an entity.
 */
export function useContentTranslations(
  entityType: string,
  entityId: string | undefined,
  fields: { fieldName: string; originalText: string | null | undefined }[]
) {
  const { i18n } = useTranslation();
  const lang = i18n.language;
  const { spokenCodes } = useSpokenLanguages();

  const { data: translations = [], isLoading } = useQuery({
    queryKey: ["content-translations-batch", entityType, entityId, lang],
    queryFn: async () => {
      if (!entityId) return [];
      const { data } = await supabase
        .from("content_translations")
        .select("field_name, translated_text, auto_generated, language_code")
        .eq("entity_type", entityType)
        .eq("entity_id", entityId);
      return data ?? [];
    },
    enabled: !!entityId && lang !== "en",
    staleTime: 5 * 60_000,
  });

  const result: Record<string, { text: string | null; isTranslated: boolean; isAuto: boolean; displayLanguage: string | null }> = {};
  for (const f of fields) {
    // Preferred language first
    const preferred = translations.find((t: any) => t.field_name === f.fieldName && t.language_code === lang);
    if (preferred) {
      result[f.fieldName] = {
        text: preferred.translated_text,
        isTranslated: true,
        isAuto: preferred.auto_generated ?? false,
        displayLanguage: lang,
      };
      continue;
    }
    // Spoken languages fallback
    let found = false;
    for (const code of spokenCodes) {
      if (code === lang || code === "en") continue;
      const match = translations.find((t: any) => t.field_name === f.fieldName && t.language_code === code);
      if (match) {
        result[f.fieldName] = {
          text: match.translated_text,
          isTranslated: true,
          isAuto: match.auto_generated ?? false,
          displayLanguage: code,
        };
        found = true;
        break;
      }
    }
    if (!found) {
      result[f.fieldName] = {
        text: f.originalText ?? null,
        isTranslated: false,
        isAuto: false,
        displayLanguage: null,
      };
    }
  }

  return { translations: result, isLoading };
}
