import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Sprout } from "lucide-react";
import { HintTooltip, HINTS } from "@/components/onboarding/ContextualHint";

/**
 * CTGEstimateBlock — shown in quest detail reward grid.
 * Calculates estimated $CTG from emission rules.
 */
export function CTGEstimateBlock({ subtaskCount }: { subtaskCount: number }) {
  const { data: estimate } = useQuery({
    queryKey: ["ctg-quest-estimate", subtaskCount],
    queryFn: async () => {
      const { data } = await supabase
        .from("ctg_emission_rules")
        .select("contribution_type, ctg_amount, commons_share_percent, is_active")
        .in("contribution_type", ["quest_completed", "subtask_completed"]);
      const rules = (data ?? []).filter((r) => r.is_active);
      const questRule = rules.find((r) => r.contribution_type === "quest_completed");
      const subRule = rules.find((r) => r.contribution_type === "subtask_completed");
      const questAmt = questRule?.ctg_amount ?? 0;
      const subAmt = subRule?.ctg_amount ?? 0;
      return questAmt + subtaskCount * subAmt;
    },
    staleTime: 60_000,
  });

  if (!estimate || estimate <= 0) return null;

  return (
    <div>
      <p className="text-xs text-muted-foreground font-medium inline-flex items-center gap-1">🌱 $CTG Estimate <HintTooltip {...HINTS.tooltips.questCTG} /></p>
      <p className="text-lg font-bold text-emerald-600 dark:text-emerald-400 flex items-center gap-1">
        <Sprout className="h-4 w-4" />
        ~{estimate} $CTG
      </p>
      <p className="text-[10px] text-muted-foreground">Earned on verified completion</p>
    </div>
  );
}

/**
 * GuildCTGStat — stat card for guild detail page.
 * Shows total $CTG generated by contributions linked to this guild.
 */
export function GuildCTGStat({ guildId }: { guildId: string }) {
  const { data: total = 0 } = useQuery({
    queryKey: ["guild-ctg-total", guildId],
    queryFn: async () => {
      // Get contribution_log IDs for this guild
      const { data: logs } = await supabase
        .from("contribution_logs")
        .select("id")
        .eq("guild_id", guildId);
      if (!logs?.length) return 0;

      const logIds = logs.map((l) => l.id);
      // Sum CTG earned from transactions linked to these contributions
      const { data: txs } = await supabase
        .from("ctg_transactions")
        .select("amount")
        .eq("type", "EARNED_CONTRIBUTION")
        .in("related_entity_id", logIds);
      return (txs ?? []).reduce((s, t) => s + Math.abs(t.amount), 0);
    },
    staleTime: 60_000,
  });

  return (
    <div className="rounded-lg border border-border bg-card p-4 text-center">
      <p className="text-2xl font-bold text-emerald-600 dark:text-emerald-400 flex items-center justify-center gap-1">
        <Sprout className="h-5 w-5" />
        {Math.round(total * 100) / 100}
      </p>
      <p className="text-sm text-muted-foreground">$CTG Generated</p>
    </div>
  );
}

/**
 * ProfileCTGStats — for user profile stats area.
 * Shows current balance and lifetime earned.
 */
export function ProfileCTGStats({
  userId,
  isOwnProfile,
}: {
  userId: string;
  isOwnProfile: boolean;
}) {
  const { data } = useQuery({
    queryKey: ["profile-ctg-stats", userId],
    queryFn: async () => {
      const { data: wallet } = await supabase
        .from("ctg_wallets")
        .select("balance, lifetime_earned")
        .eq("user_id", userId)
        .maybeSingle();
      return wallet;
    },
    staleTime: 30_000,
  });

  if (!data) return null;

  return (
    <div className="flex items-center gap-3">
      {isOwnProfile && (
        <div className="flex items-center gap-1 text-sm">
          <Sprout className="h-3.5 w-3.5 text-emerald-600" />
          <span className="font-semibold tabular-nums">{data.balance.toLocaleString("fr-FR", { maximumFractionDigits: 2 })}</span>
          <span className="text-muted-foreground text-xs">$CTG</span>
        </div>
      )}
      <div className="flex items-center gap-1 text-sm">
        <span>{getStewardTier(data.lifetime_earned).icon}</span>
        <span className="text-muted-foreground text-xs">Lifetime:</span>
        <span className="font-semibold tabular-nums">{data.lifetime_earned.toLocaleString("fr-FR", { maximumFractionDigits: 2 })}</span>
        <span className="text-muted-foreground text-xs">$CTG earned</span>
      </div>
    </div>
  );
}
