export enum UserRole {
  GAMECHANGER = "GAMECHANGER",
  ECOSYSTEM_BUILDER = "ECOSYSTEM_BUILDER",
  BOTH = "BOTH",
}

export enum GuildType {
  GUILD = "GUILD",
  NETWORK = "NETWORK",
  COLLECTIVE = "COLLECTIVE",
}

export enum GuildMemberRole {
  ADMIN = "ADMIN",
  MEMBER = "MEMBER",
}

export enum QuestStatus {
  DRAFT = "DRAFT",
  OPEN = "OPEN",
  OPEN_FOR_PROPOSALS = "OPEN_FOR_PROPOSALS",
  ACTIVE = "ACTIVE",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum ProposalStatus {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  WITHDRAWN = "WITHDRAWN",
}

export enum FundingType {
  CREDITS = "CREDITS",
  FIAT = "FIAT",
}

export enum FundingStatus {
  PLEDGED = "PLEDGED",
  PAID = "PAID",
  CANCELLED = "CANCELLED",
}

export enum MonetizationType {
  FREE = "FREE",
  PAID = "PAID",
  MIXED = "MIXED",
}

export enum QuestParticipantRole {
  OWNER = "OWNER",
  COLLABORATOR = "COLLABORATOR",
  FOLLOWER = "FOLLOWER",
}

export enum QuestParticipantStatus {
  INVITED = "INVITED",
  ACCEPTED = "ACCEPTED",
  DECLINED = "DECLINED",
}

export enum QuestUpdateType {
  GENERAL = "GENERAL",
  CALL_FOR_HELP = "CALL_FOR_HELP",
  MILESTONE = "MILESTONE",
  REFLECTION = "REFLECTION",
}

export enum TerritoryLevel {
  TOWN = "TOWN",
  REGION = "REGION",
  NATIONAL = "NATIONAL",
  OTHER = "OTHER",
}

export enum CommentTargetType {
  USER = "USER",
  GUILD = "GUILD",
  QUEST = "QUEST",
  QUEST_UPDATE = "QUEST_UPDATE",
  ACHIEVEMENT = "ACHIEVEMENT",
  POD = "POD",
  SERVICE = "SERVICE",
  COMPANY = "COMPANY",
}

export enum NotificationType {
  // Legacy (kept for backward compat)
  COMMENT = "COMMENT",
  UPVOTE = "UPVOTE",
  INVITE = "INVITE",
  QUEST_UPDATE = "QUEST_UPDATE",
  BOOKING = "BOOKING",
  // Quest
  QUEST_CREATED = "QUEST_CREATED",
  QUEST_UPDATED = "QUEST_UPDATED",
  QUEST_COMMENT = "QUEST_COMMENT",
  QUEST_UPVOTE = "QUEST_UPVOTE",
  QUEST_COMPLETED = "QUEST_COMPLETED",
  // Quest Proposals & Funding
  QUEST_PROPOSAL_SUBMITTED = "QUEST_PROPOSAL_SUBMITTED",
  QUEST_PROPOSAL_ACCEPTED = "QUEST_PROPOSAL_ACCEPTED",
  QUEST_PROPOSAL_REJECTED = "QUEST_PROPOSAL_REJECTED",
  QUEST_FUNDED_CREDITS = "QUEST_FUNDED_CREDITS",
  QUEST_FUNDED_FIAT = "QUEST_FUNDED_FIAT",
  // Guild
  GUILD_MEMBER_ADDED = "GUILD_MEMBER_ADDED",
  GUILD_ROLE_CHANGED = "GUILD_ROLE_CHANGED",
  GUILD_QUEST_CREATED = "GUILD_QUEST_CREATED",
  // Pod
  POD_CREATED = "POD_CREATED",
  POD_MESSAGE = "POD_MESSAGE",
  // Booking granular
  BOOKING_REQUESTED = "BOOKING_REQUESTED",
  BOOKING_CONFIRMED = "BOOKING_CONFIRMED",
  BOOKING_CANCELLED = "BOOKING_CANCELLED",
  BOOKING_UPDATED = "BOOKING_UPDATED",
  BOOKING_REQUIRES_PAYMENT = "BOOKING_REQUIRES_PAYMENT",
  // Follow
  FOLLOWER_NEW = "FOLLOWER_NEW",
  FOLLOWER_ACTIVITY = "FOLLOWER_ACTIVITY",
  // Messaging
  MESSAGE_PRIVATE = "MESSAGE_PRIVATE",
  // Gamification
  XP_GAINED = "XP_GAINED",
  ACHIEVEMENT_UNLOCKED = "ACHIEVEMENT_UNLOCKED",
  // Admin / System
  REPORT_STATUS_UPDATED = "REPORT_STATUS_UPDATED",
  SYSTEM_ANNOUNCEMENT = "SYSTEM_ANNOUNCEMENT",
}

export enum NotificationEntityType {
  QUEST = "QUEST",
  QUEST_UPDATE = "QUEST_UPDATE",
  COMMENT = "COMMENT",
  GUILD = "GUILD",
  POD = "POD",
  BOOKING = "BOOKING",
  SERVICE = "SERVICE",
  USER = "USER",
  ACHIEVEMENT = "ACHIEVEMENT",
  COMPANY = "COMPANY",
  SYSTEM = "SYSTEM",
}

export enum FollowTargetType {
  USER = "USER",
  GUILD = "GUILD",
  QUEST = "QUEST",
  COMPANY = "COMPANY",
  POD = "POD",
  SERVICE = "SERVICE",
  COURSE = "COURSE",
  EVENT = "EVENT",
  TERRITORY = "TERRITORY",
}

export enum PodType {
  QUEST_POD = "QUEST_POD",
  STUDY_POD = "STUDY_POD",
}

export enum PodMemberRole {
  HOST = "HOST",
  MEMBER = "MEMBER",
}

export enum BookingStatus {
  REQUESTED = "REQUESTED",
  PENDING_PAYMENT = "PENDING_PAYMENT",
  CONFIRMED = "CONFIRMED",
  ACCEPTED = "ACCEPTED",
  DECLINED = "DECLINED",
  CANCELLED = "CANCELLED",
  COMPLETED = "COMPLETED",
}

export enum OnlineLocationType {
  JITSI = "JITSI",
  ZOOM = "ZOOM",
  OTHER = "OTHER",
}

export enum PaymentStatus {
  NOT_REQUIRED = "NOT_REQUIRED",
  PENDING = "PENDING",
  PAID = "PAID",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
}

export enum CompanySize {
  MICRO = "MICRO",
  SME = "SME",
  LARGE = "LARGE",
  OTHER = "OTHER",
}

export enum TopicStewardRole {
  STEWARD = "STEWARD",
  CURATOR = "CURATOR",
}

export enum TopicFeatureTargetType {
  QUEST = "QUEST",
  GUILD = "GUILD",
}

export enum ReportTargetType {
  USER = "USER",
  GUILD = "GUILD",
  QUEST = "QUEST",
  POD = "POD",
  SERVICE = "SERVICE",
  COMMENT = "COMMENT",
  BOOKING = "BOOKING",
}

export enum ReportStatus {
  OPEN = "OPEN",
  REVIEWED = "REVIEWED",
  RESOLVED = "RESOLVED",
  DISMISSED = "DISMISSED",
}

export enum AttachmentTargetType {
  QUEST = "QUEST",
  QUEST_UPDATE = "QUEST_UPDATE",
  POD = "POD",
  GUILD = "GUILD",
  COMPANY = "COMPANY",
  LESSON = "LESSON",
}

export enum CourseLevel {
  BEGINNER = "BEGINNER",
  INTERMEDIATE = "INTERMEDIATE",
  ADVANCED = "ADVANCED",
}

export enum CoursePurchaseStatus {
  PENDING = "PENDING",
  PAID = "PAID",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
}

export enum GuildJoinPolicy {
  OPEN = "OPEN",
  APPROVAL_REQUIRED = "APPROVAL_REQUIRED",
  INVITE_ONLY = "INVITE_ONLY",
}

export enum GuildApplicationStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}
