// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireAuth(ctx) {
  return ctx.isAuthenticated() ? ctx.getUserId() ?? null : null;
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function dataResult(structured) {
  return {
    content: [{ type: "text", text: JSON.stringify(structured, null, 2) }],
    structuredContent: structured
  };
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the changethegame profile of the signed-in user: name, headline, XP, level and wallet balances (Coins, $CTG, Credits, Biopoints).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const userId = requireAuth(ctx);
    if (!userId) return errorResult("Not authenticated.");
    const { data, error } = await supabaseForUser(ctx).from("profiles").select(
      "user_id, name, headline, bio, location, xp_total, xp_level, coins_balance, ctg_balance, credits_balance, biopoints_balance, persona_type, current_plan_code"
    ).eq("user_id", userId).maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("No profile found for this account.");
    return dataResult({ profile: data });
  }
});

// src/lib/mcp/tools/search-quests.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var search_quests_default = defineTool2({
  name: "search_quests",
  title: "Search quests",
  description: "Search visible changethegame quests by keyword across title and description, optionally filtered by status or guild.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Keyword to look for in quest titles and descriptions."),
    status: z.enum(["OPEN", "IN_PROGRESS", "COMPLETED", "OPEN_FOR_PROPOSALS", "ACTIVE", "IDEA"]).optional().describe("Restrict results to this quest status."),
    guild_id: z.string().uuid().optional().describe("Restrict results to quests owned by this guild."),
    limit: z.number().int().min(1).max(50).default(10).describe("Maximum number of quests to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, status, guild_id, limit }, ctx) => {
    if (!requireAuth(ctx)) return errorResult("Not authenticated.");
    const escaped = query.replace(/[%,()]/g, " ").trim();
    let q = supabaseForUser(ctx).from("quests").select("id, title, description, status, guild_id, reward_xp, ctg_budget, coins_budget, created_at").eq("is_deleted", false).eq("is_draft", false).or(`title.ilike.%${escaped}%,description.ilike.%${escaped}%`).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (status) q = q.eq("status", status);
    if (guild_id) q = q.eq("guild_id", guild_id);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return dataResult({ count: data?.length ?? 0, quests: data ?? [] });
  }
});

// src/lib/mcp/tools/get-quest.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_quest_default = defineTool3({
  name: "get_quest",
  title: "Get quest detail",
  description: "Fetch one quest with its subtasks, participants and recent updates. Use search_quests or list_my_quests first to get the quest id.",
  inputSchema: {
    quest_id: z2.string().uuid().describe("The quest id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ quest_id }, ctx) => {
    if (!requireAuth(ctx)) return errorResult("Not authenticated.");
    const supabase = supabaseForUser(ctx);
    const { data: quest, error } = await supabase.from("quests").select(
      "id, title, description, status, quest_nature, guild_id, owner_type, owner_id, reward_xp, credit_reward, ctg_budget, coins_budget, funding_goal_credits, ai_summary, created_at, updated_at"
    ).eq("id", quest_id).maybeSingle();
    if (error) return errorResult(error.message);
    if (!quest) return errorResult("Quest not found or not visible to you.");
    const [subtasks, participants, updates] = await Promise.all([
      supabase.from("quest_subtasks").select("id, title, status, priority, due_date, assignee_user_ids, xp_reward, ctg_reward, order_index").eq("quest_id", quest_id).order("order_index", { ascending: true }).limit(100),
      supabase.from("quest_participants").select("user_id, role, status, created_at").eq("quest_id", quest_id).limit(100),
      supabase.from("quest_updates").select("id, content, created_at").eq("quest_id", quest_id).order("created_at", { ascending: false }).limit(10)
    ]);
    return dataResult({
      quest,
      subtasks: subtasks.data ?? [],
      participants: participants.data ?? [],
      recent_updates: updates.data ?? []
    });
  }
});

// src/lib/mcp/tools/list-my-quests.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_quests_default = defineTool4({
  name: "list_my_quests",
  title: "List my quests",
  description: "List the quests the signed-in user created or participates in, most recent first.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(20).describe("Maximum number of quests to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    const userId = requireAuth(ctx);
    if (!userId) return errorResult("Not authenticated.");
    const supabase = supabaseForUser(ctx);
    const max = limit ?? 20;
    const [created, joined] = await Promise.all([
      supabase.from("quests").select("id, title, status, guild_id, created_at").eq("created_by_user_id", userId).eq("is_deleted", false).order("created_at", { ascending: false }).limit(max),
      supabase.from("quest_participants").select("role, status, quests!inner(id, title, status, guild_id, created_at, is_deleted)").eq("user_id", userId).limit(max)
    ]);
    if (created.error) return errorResult(created.error.message);
    const participating = (joined.data ?? []).map((row) => {
      const quest = row.quests;
      return quest && quest.is_deleted === false ? { ...quest, my_role: row.role, my_status: row.status } : null;
    }).filter(Boolean);
    return dataResult({ created: created.data ?? [], participating });
  }
});

// src/lib/mcp/tools/list-my-guilds.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_my_guilds_default = defineTool5({
  name: "list_my_guilds",
  title: "List my guilds",
  description: "List the guilds, networks and collectives the signed-in user is a member of, with their role in each.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).default(50).describe("Maximum number of guilds to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    const userId = requireAuth(ctx);
    if (!userId) return errorResult("Not authenticated.");
    const { data, error } = await supabaseForUser(ctx).from("guild_members").select("role, joined_at, guilds!inner(id, name, description, type, is_deleted)").eq("user_id", userId).limit(limit ?? 50);
    if (error) return errorResult(error.message);
    const guilds = (data ?? []).map((row) => {
      const guild = row.guilds;
      return guild && guild.is_deleted === false ? { id: guild.id, name: guild.name, description: guild.description, type: guild.type, my_role: row.role, joined_at: row.joined_at } : null;
    }).filter(Boolean);
    return dataResult({ count: guilds.length, guilds });
  }
});

// src/lib/mcp/tools/list-my-tasks.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_my_tasks_default = defineTool6({
  name: "list_my_tasks",
  title: "List my tasks",
  description: "List the signed-in user's open work: personal tasks plus quest subtasks assigned to them.",
  inputSchema: {
    include_done: z5.boolean().default(false).describe("Include tasks already marked as done."),
    limit: z5.number().int().min(1).max(100).default(30).describe("Maximum number of items per list.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_done, limit }, ctx) => {
    const userId = requireAuth(ctx);
    if (!userId) return errorResult("Not authenticated.");
    const supabase = supabaseForUser(ctx);
    const max = limit ?? 30;
    let personalQuery = supabase.from("personal_tasks").select("id, title, description, status, priority, due_date, created_at").eq("user_id", userId).order("created_at", { ascending: false }).limit(max);
    if (!include_done) personalQuery = personalQuery.neq("status", "done");
    let subtaskQuery = supabase.from("quest_subtasks").select("id, quest_id, title, status, priority, due_date, xp_reward, ctg_reward").contains("assignee_user_ids", [userId]).order("due_date", { ascending: true }).limit(max);
    if (!include_done) subtaskQuery = subtaskQuery.neq("status", "done");
    const [personal, subtasks] = await Promise.all([personalQuery, subtaskQuery]);
    if (personal.error) return errorResult(personal.error.message);
    return dataResult({
      personal_tasks: personal.data ?? [],
      assigned_quest_subtasks: subtasks.data ?? []
    });
  }
});

// src/lib/mcp/tools/create-personal-task.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^3.25.76";
var create_personal_task_default = defineTool7({
  name: "create_personal_task",
  title: "Create personal task",
  description: "Create a private personal task on the signed-in user's changethegame to-do list.",
  inputSchema: {
    title: z6.string().trim().min(1).max(200).describe("Short task title."),
    description: z6.string().trim().max(2e3).optional().describe("Optional task details."),
    priority: z6.enum(["low", "medium", "high"]).default("medium").describe("Task priority."),
    due_date: z6.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Optional due date in YYYY-MM-DD format.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, description, priority, due_date }, ctx) => {
    const userId = requireAuth(ctx);
    if (!userId) return errorResult("Not authenticated.");
    const { data, error } = await supabaseForUser(ctx).from("personal_tasks").insert({
      user_id: userId,
      title,
      description: description ?? null,
      priority: priority ?? "medium",
      due_date: due_date ?? null,
      status: "todo"
    }).select("id, title, status, priority, due_date").single();
    if (error) return errorResult(error.message);
    return dataResult({ created: data });
  }
});

// src/lib/mcp/tools/update-personal-task.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z7 } from "npm:zod@^3.25.76";
var update_personal_task_default = defineTool8({
  name: "update_personal_task",
  title: "Update personal task",
  description: "Update the status, priority or due date of one of the signed-in user's personal tasks.",
  inputSchema: {
    task_id: z7.string().uuid().describe("The personal task id (from list_my_tasks)."),
    status: z7.enum(["todo", "in_progress", "done"]).optional().describe("New status."),
    priority: z7.enum(["low", "medium", "high"]).optional().describe("New priority."),
    due_date: z7.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("New due date in YYYY-MM-DD format.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ task_id, status, priority, due_date }, ctx) => {
    const userId = requireAuth(ctx);
    if (!userId) return errorResult("Not authenticated.");
    const patch = {};
    if (status) patch.status = status;
    if (priority) patch.priority = priority;
    if (due_date) patch.due_date = due_date;
    if (Object.keys(patch).length === 0) return errorResult("Nothing to update.");
    const { data, error } = await supabaseForUser(ctx).from("personal_tasks").update(patch).eq("id", task_id).eq("user_id", userId).select("id, title, status, priority, due_date").maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Task not found or not yours.");
    return dataResult({ updated: data });
  }
});

// src/lib/mcp/index.ts
var projectRef = "anzeimppqytonfxrnqxp";
var mcp_default = defineMcp({
  name: "changethegame",
  title: "changethegame",
  version: "0.1.0",
  instructions: "Tools for changethegame, a regenerative collaboration platform of quests, guilds and territories. Every call acts as the signed-in human: use `whoami` for their profile and balances, `list_my_quests` / `list_my_guilds` / `list_my_tasks` for their commitments, `search_quests` and `get_quest` to explore work, and the personal-task tools to manage their to-do list. All data is scoped by the platform's access rules \u2014 only what this user may see is returned.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    search_quests_default,
    get_quest_default,
    list_my_quests_default,
    list_my_guilds_default,
    list_my_tasks_default,
    create_personal_task_default,
    update_personal_task_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
