
INSERT INTO milestones (code, title, description, icon, reward_type, reward_amount, persona_visibility, trigger_type, trigger_config, sort_order, phase, subtitle) VALUES
('complete_profile_v2', 'Complete your profile', 'Fill in your name, bio, avatar and headline', '👤', 'XP', 25, 'ALL', 'SYSTEM_STATE', '{}', 1, 'discover', 'At least 70% complete'),
('explore_guilds', 'Explore guilds', 'Browse the guilds directory', '🔍', 'XP', 10, 'ALL', 'USER_ACTION', '{}', 2, 'discover', NULL),
('join_first_guild_v2', 'Join your first guild', 'Become a member of any guild', '🏰', 'XP', 30, 'ALL', 'SYSTEM_STATE', '{}', 3, 'discover', NULL),
('first_comment', 'Leave your first comment', 'Comment on any post, quest or discussion', '💬', 'XP', 15, 'ALL', 'USER_ACTION', '{}', 4, 'discover', NULL),
('follow_3_quests', 'Follow 3 quests', 'Stay updated on quests that interest you', '⭐', 'XP', 20, 'ALL', 'USER_ACTION', '{}', 5, 'discover', NULL),
('visit_territory', 'Visit a territory', 'Explore your local or thematic territory', '🗺️', 'XP', 10, 'ALL', 'USER_ACTION', '{}', 6, 'discover', NULL),
('read_guide', 'Read a guide', 'Learn the basics from our knowledge base', '📖', 'XP', 10, 'ALL', 'USER_ACTION', '{}', 7, 'discover', NULL),
('set_spoken_languages', 'Set your spoken languages', 'Help others know how to communicate with you', '🌐', 'XP', 10, 'ALL', 'SYSTEM_STATE', '{}', 8, 'discover', NULL),
('explore_services', 'Explore services', 'Browse the services marketplace', '🛒', 'XP', 10, 'ALL', 'USER_ACTION', '{}', 9, 'discover', NULL),
('view_user_profile', 'View another user profile', 'Discover people in the network', '👁️', 'XP', 5, 'ALL', 'USER_ACTION', '{}', 10, 'discover', NULL),
('follow_user', 'Follow a user', 'Stay updated on someone''s activity', '➕', 'XP', 10, 'ALL', 'USER_ACTION', '{}', 11, 'discover', NULL),
('send_first_message', 'Send your first message', 'Start a conversation with someone', '✉️', 'XP', 15, 'ALL', 'USER_ACTION', '{}', 12, 'discover', NULL),
('respond_opportunity', 'Respond to an opportunity', 'Apply or express interest in a quest need', '🙋', 'XP', 20, 'ALL', 'USER_ACTION', '{}', 20, 'contribute', NULL),
('join_quest', 'Join a quest', 'Become a participant in someone''s quest', '⚔️', 'XP', 25, 'ALL', 'USER_ACTION', '{}', 21, 'contribute', NULL),
('complete_subtask', 'Complete a subtask', 'Finish your first assigned task', '✅', 'XP', 20, 'ALL', 'USER_ACTION', '{}', 22, 'contribute', NULL),
('log_contribution', 'Log a contribution', 'Record your work in the contribution log', '📝', 'XP', 20, 'ALL', 'USER_ACTION', '{}', 23, 'contribute', NULL),
('add_knowledge', 'Add knowledge to a territory', 'Share a memory or resource', '🧠', 'XP', 20, 'ALL', 'SYSTEM_STATE', '{}', 24, 'contribute', NULL),
('join_event', 'Attend an event', 'Join an online or in-person event', '📅', 'XP', 15, 'ALL', 'SYSTEM_STATE', '{}', 25, 'contribute', NULL),
('react_discussion', 'React to a discussion', 'Upvote or react to community content', '👍', 'XP', 5, 'ALL', 'USER_ACTION', '{}', 26, 'contribute', NULL),
('help_or_resource', 'Offer help or a resource', 'Contribute to a quest you didn''t create', '🤝', 'XP', 25, 'ALL', 'USER_ACTION', '{}', 27, 'contribute', NULL),
('fund_quest', 'Fund a quest', 'Support a quest financially', '💰', 'CREDITS', 10, 'ALL', 'USER_ACTION', '{}', 28, 'contribute', NULL),
('give_trust', 'Give trust to someone', 'Endorse another member''s contribution', '🫶', 'XP', 10, 'ALL', 'USER_ACTION', '{}', 29, 'contribute', NULL),
('book_service', 'Book a service', 'Book a service from the marketplace', '📞', 'XP', 15, 'ALL', 'USER_ACTION', '{}', 30, 'contribute', NULL),
('join_second_guild', 'Join a second guild', 'Expand your network across guilds', '🏰', 'XP', 20, 'ALL', 'SYSTEM_STATE', '{}', 31, 'contribute', NULL),
('complete_5_subtasks', 'Complete 5 subtasks', 'Show consistent contribution', '🏅', 'XP', 50, 'ALL', 'USER_ACTION', '{}', 32, 'contribute', 'Across any quests'),
('get_contribution_verified', 'Get a contribution verified', 'Have your work reviewed and approved', '✔️', 'XP', 30, 'ALL', 'USER_ACTION', '{}', 33, 'contribute', NULL),
('follow_quest_v2', 'Follow a quest', 'Stay updated on a quest''s progress', '👀', 'XP', 10, 'ALL', 'USER_ACTION', '{}', 34, 'contribute', NULL),
('create_quest', 'Create a quest', 'Launch your own quest or project', '🚀', 'XP', 40, 'ALL', 'SYSTEM_STATE', '{}', 40, 'create', NULL),
('publish_service_v2', 'Publish a service', 'Offer your skills on the marketplace', '🛠️', 'XP', 30, 'ALL', 'SYSTEM_STATE', '{}', 41, 'create', NULL),
('invite_collaborator', 'Invite a collaborator', 'Bring someone into your quest or guild', '📨', 'XP', 20, 'ALL', 'USER_ACTION', '{}', 42, 'create', NULL),
('post_update', 'Post a quest update', 'Share progress on your quest', '📣', 'XP', 15, 'ALL', 'USER_ACTION', '{}', 43, 'create', NULL),
('create_event', 'Create an event', 'Host an event through your guild', '🎉', 'XP', 25, 'ALL', 'SYSTEM_STATE', '{}', 44, 'create', NULL),
('create_course', 'Publish a course', 'Share your knowledge as a structured course', '🎓', 'XP', 35, 'ALL', 'SYSTEM_STATE', '{}', 45, 'create', NULL),
('open_fundraising', 'Open fundraising on a quest', 'Enable financial support for your quest', '💸', 'XP', 20, 'ALL', 'USER_ACTION', '{}', 46, 'create', NULL),
('set_availability', 'Set your availability', 'Let people know when you''re available', '🕐', 'XP', 15, 'ALL', 'USER_ACTION', '{}', 47, 'create', NULL),
('add_quest_needs', 'Add needs to your quest', 'Define what your quest requires', '📋', 'XP', 15, 'ALL', 'USER_ACTION', '{}', 48, 'create', NULL),
('receive_first_proposal', 'Receive your first proposal', 'Get someone interested in your quest', '📩', 'XP', 20, 'ALL', 'USER_ACTION', '{}', 49, 'create', NULL),
('quest_with_3_participants', 'Quest with 3+ participants', 'Build a collaborative team', '👥', 'XP', 40, 'ALL', 'USER_ACTION', '{}', 50, 'create', 'On any single quest'),
('complete_first_quest', 'Complete your first quest', 'Finish a quest you created or participated in', '🏆', 'CREDITS', 25, 'ALL', 'USER_ACTION', '{}', 51, 'create', NULL),
('earn_100_xp', 'Earn 100 XP', 'Reach the 100 XP milestone', '⚡', 'BADGE', 0, 'ALL', 'SYSTEM_STATE', '{}', 52, 'create', NULL),
('create_guild_v2', 'Create a guild', 'Found your own guild or organization', '🏗️', 'XP', 50, 'ALL', 'USER_ACTION', '{}', 60, 'structure', NULL),
('become_admin', 'Become a guild admin', 'Take on a leadership role', '👑', 'XP', 25, 'ALL', 'USER_ACTION', '{}', 61, 'structure', NULL),
('governance_vote', 'Vote on governance', 'Participate in a guild decision', '🗳️', 'XP', 20, 'ALL', 'USER_ACTION', '{}', 62, 'structure', NULL),
('setup_contract', 'Set up a quest contract', 'Formalize a collaboration agreement', '📜', 'XP', 30, 'ALL', 'USER_ACTION', '{}', 63, 'structure', NULL),
('configure_exit', 'Configure exit terms', 'Set contributor exit conditions', '🚪', 'XP', 20, 'ALL', 'USER_ACTION', '{}', 64, 'structure', NULL),
('create_partnership', 'Create a guild partnership', 'Connect your guild with another', '🤝', 'XP', 30, 'ALL', 'USER_ACTION', '{}', 65, 'structure', NULL),
('freeze_pie', 'Freeze the pie', 'Lock equity distribution on a quest', '🥧', 'XP', 25, 'ALL', 'USER_ACTION', '{}', 66, 'structure', NULL),
('distribute_rewards', 'Distribute rewards', 'Send rewards to contributors', '🎁', 'XP', 25, 'ALL', 'USER_ACTION', '{}', 67, 'structure', NULL),
('guild_10_members', 'Guild with 10+ members', 'Grow your guild to 10 members', '🌟', 'CREDITS', 50, 'ALL', 'USER_ACTION', '{}', 68, 'structure', 'Any guild you admin'),
('become_shareholder_v2', 'Become a shareholder', 'Earn equity in a quest', '📈', 'XP', 40, 'ALL', 'SYSTEM_STATE', '{}', 69, 'structure', NULL)
ON CONFLICT (code) DO UPDATE SET
  phase = EXCLUDED.phase,
  subtitle = EXCLUDED.subtitle,
  sort_order = EXCLUDED.sort_order,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  reward_type = EXCLUDED.reward_type,
  reward_amount = EXCLUDED.reward_amount;

-- Update legacy milestones with phases
UPDATE milestones SET phase = 'discover' WHERE code IN ('complete_profile', 'add_spoken_languages', 'join_first_guild', 'join_creative_circle', 'impact_guild');
UPDATE milestones SET phase = 'contribute' WHERE code IN ('collaborate_pod', 'contribute_territory', 'attend_event', 'impact_territory_memory');
UPDATE milestones SET phase = 'create' WHERE code IN ('create_first_quest', 'publish_service', 'publish_course', 'creative_artwork_quest', 'creative_class', 'impact_quest', 'host_workshop');
UPDATE milestones SET phase = 'structure' WHERE code IN ('become_shareholder', 'invite_friend');
