
ALTER TABLE ctg_transactions DROP CONSTRAINT ctg_transactions_type_check;
ALTER TABLE ctg_transactions ADD CONSTRAINT ctg_transactions_type_check CHECK (type = ANY (ARRAY[
  'EARNED_QUEST', 'EARNED_SUBTASK', 'EARNED_SERVICE', 'EARNED_RITUAL',
  'EARNED_GOVERNANCE', 'EARNED_MENTORSHIP', 'EARNED_CONTRIBUTION',
  'EARNED_REVIEW', 'EARNED_DOCUMENTATION', 'EARNED_ECOLOGICAL',
  'EARNED_BOUNTY', 'EARNED_GUILD', 'EARNED_PROFILE', 'EARNED_TRUST',
  'EARNED_COMMENT', 'EARNED_POST', 'EARNED_COURSE', 'EARNED_EVENT',
  'EARNED_NATURAL_SYSTEM',
  'TRANSFER_IN', 'TRANSFER_OUT', 'EXCHANGE_TO_CREDITS',
  'DEMURRAGE', 'COMMONS_EMISSION', 'ADMIN_GRANT', 'ADMIN_DEDUCT'
]));
